{% set name = "sentinelhub" %}
{% set version = "3.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c58aad1d8c35a1e2697c3a29515fcf99265b30d03a685be1ba106f4a7e58ce22
build:
  noarch: python
  number: 0
  entry_points:
    - sentinelhub=sentinelhub.commands:main_help
    - sentinelhub.aws=sentinelhub.aws.commands:aws
    - sentinelhub.config=sentinelhub.commands:config
    - sentinelhub.download=sentinelhub.commands:download
  script: {{ PYTHON }} -m pip install . -vv
requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling

  run:
    - aenum >=2.1.4
    - boto3
    - botocore
    - click
    - dataclasses-json
    - hatchling
    - numpy
    - oauthlib
    - pillow >=9.2.0
    - pyproj >=2.2.0
    - python >={{ python_min }}
    - python-dateutil
    - requests >=2.27.0
    - requests-oauthlib >=1.0.0
    - shapely
    - tifffile >=2020.9.30
    - tomli
    - tomli-w
    - tqdm
    - typing-extensions
    - utm

test:
  requires:
    - python {{ python_min }}
  imports:
    - sentinelhub
    - sentinelhub.aws
    - sentinelhub.download
  commands:
    - sentinelhub --help
    - sentinelhub.aws --help
    - sentinelhub.config --help
    - sentinelhub.download --help

about:
  home: https://github.com/sentinel-hub/sentinelhub-py
  license: CC-BY-SA-4.0
  license_family: CC
  license_file: LICENSE.md
  summary: Sentinel Hub Utilities
  doc_url: https://pypi.org/project/sentinelhub/
  dev_url: https://github.com/sentinel-hub/sentinelhub-py

extra:
  recipe-maintainers:
    - tsuligoj
    - mlubej
    - zigaluksic
    - bubblyorca
    - mxr-conda
    - zigaluksic
