{% set name = "sentinelhub" %}
{% set version = "3.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfe05b76644381ba070f7790aece0bdeca5eaa0263b2da7882076f73a60b74c4
build:
  noarch: python
  number: 0
  entry_points:
    - sentinelhub=sentinelhub.commands:main_help
    - sentinelhub.aws=sentinelhub.aws.commands:aws
    - sentinelhub.config=sentinelhub.commands:config
    - sentinelhub.download=sentinelhub.commands:download
  script: {{ PYTHON }} -m pip install . -vv
requirements:
  host:
    - pip
    - python >=3.7

  run:
    - aenum >=2.1.4
    - boto3
    - botocore
    - click
    - numpy
    - oauthlib
    - pillow >=9.2.0
    - pyproj >=2.2.0
    - python >=3.7
    - python-dateutil
    - requests >=2.27.0
    - requests-oauthlib >=1.0.0
    - shapely
    - shared-memory38
    - tifffile >=2020.9.30
    - tqdm
    - typing-extensions
    - utm
    - dataclasses-json

test:
  imports:
    - sentinelhub
    - sentinelhub.aws
    - sentinelhub.download
  commands:
    - sentinelhub --help
    - sentinelhub.aws --help
    - sentinelhub.config --help
    - sentinelhub.download --help

about:
  home: https://github.com/sentinel-hub/sentinelhub-py
  license: CC-BY-SA-4.0
  license_family: CC
  license_file: LICENSE.md
  summary: Sentinel Hub Utilities
  doc_url: https://pypi.org/project/sentinelhub/
  dev_url: https://github.com/sentinel-hub/sentinelhub-py

extra:
  recipe-maintainers:
    - zigaluksic
    - bubblyorca
    - mxr-conda
    - zigaluksic
